// --- src/pages/SelfPublishingPage.js ---
import { UploadCloudIcon, GlobeIcon, DollarSignIcon } from '../components/icons';

const SelfPublishingPage = ({ navigateTo }) => {
    const features = [
        { icon: <UploadCloudIcon className="w-10 h-10 text-[#6C63FF]" />, title: "Upload Your Manuscript", description: "Easily upload your book in common formats like .docx or .pdf. Our system will handle the conversion." },
        { icon: <GlobeIcon className="w-10 h-10 text-[#6C63FF]" />, title: "Reach a Global Audience", description: "Publish your work on porboi.in and make it available to readers around the world." },
        { icon: <DollarSignIcon className="w-10 h-10 text-[#6C63FF]" />, title: "Earn Competitive Royalties", description: "Keep a significant portion of your earnings with our transparent and author-friendly royalty structure." }
    ];
    return (<div className="bg-white"><div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 text-center"><h1 className="text-4xl sm:text-5xl font-bold text-gray-800">Bring Your Story to Life</h1><p className="mt-4 max-w-2xl mx-auto text-lg text-gray-600">Porboi.in offers a simple, powerful platform for independent authors to publish their work and reach a global audience.</p><button className="mt-8 bg-[#EF6B4A] text-white font-bold py-4 px-8 rounded-lg text-lg hover:bg-[#e05a39] transition-colors shadow-lg">Get Started Now</button></div><div className="bg-gray-50 py-20"><div className="container mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-center text-gray-800 mb-12">How It Works</h2><div className="grid md:grid-cols-3 gap-12 text-center"><div className="flex flex-col items-center"><div className="flex items-center justify-center w-20 h-20 bg-white rounded-full shadow-md mb-4"><UploadCloudIcon className="w-10 h-10 text-[#6C63FF]" /></div><h3 className="text-xl font-semibold mb-2">1. Upload & Format</h3><p className="text-gray-600">Submit your manuscript and cover art. Our tools help you format it for a professional look.</p></div><div className="flex flex-col items-center"><div className="flex items-center justify-center w-20 h-20 bg-white rounded-full shadow-md mb-4"><GlobeIcon className="w-10 h-10 text-[#6C63FF]" /></div><h3 className="text-xl font-semibold mb-2">2. Set Your Price & Publish</h3><p className="text-gray-600">You have full control over your book's pricing. Hit publish and your book goes live in our store.</p></div><div className="flex flex-col items-center"><div className="flex items-center justify-center w-20 h-20 bg-white rounded-full shadow-md mb-4"><DollarSignIcon className="w-10 h-10 text-[#6C63FF]" /></div><h3 className="text-xl font-semibold mb-2">3. Start Earning</h3><p className="text-gray-600">Track your sales through our author dashboard and receive monthly royalty payments.</p></div></div></div></div></div>);
};
export default SelfPublishingPage;